config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cakes#index"

  post 'cakes/calculate_cake', to: 'cakes#calculate_cake'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
    def index
        @cake_result = params[:cake_result]
    end

    def calculate_cake 
        begin
            # Transform recipe and ingredients to correct format for the helper function
            recipe = {}
            ingredients = {}
            params[:recipe].values.each { |r| recipe["#{r[:key]}"] = r[:value].to_i }
            params[:ingredients].values.each { |i| ingredients["#{i[:key]}"] = i[:value].to_i }
            
            @result = ApplicationController.helpers.cakes(recipe , ingredients)
            
            redirect_to root_path(cake_result: @result, params: request.parameters)
        rescue => error
            redirect_back(fallback_location: root_path, notice: error)
        end 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
    def cakes(recipe, ingredients)
        if recipe.class == Hash && ingredients.class == Hash # Validate correct inputs
            # total of cakes we can make is the minimun of ingredients present
            @total = -1

            recipe.keys.each do |i|
                if ingredients[i] != nil 
                    if ingredients[i].class == Integer && recipe[i].class == Integer # Validate unit of ingredients
                        individual_ingredients = ingredients[i] / recipe[i]
                        @total = @total == -1 || individual_ingredients < @total ? individual_ingredients : @total 
                    else
                        raise 'This function only accept integer in values of keys'
                    end
                else # finded nissing ingredients
                    return 0
                end 
            end

            return @total
        else
            raise 'invalid inputs type'
        end
    end
end

app/views/cakes/_ingredients.html.erb
<div class="card">
    <div class="card-body" >
        <h4>Ingredients:</h4>
        <div id="ingredients">
            <% if params['ingredients'].present? %>
                <% i_index = 0 %>
                <% params['ingredients'].each do |i| %>
                    <% i_index += 1 %>
                    <div class="row ingredient_item <%= "ingredients-#{i_index}" %>">
                        <div class="col">
                            <div class="mb-3">
                                <%= label_tag "ingredients[#{i_index}][key]","name", class: "form-label" %>
                                <%= text_field_tag "ingredients[#{i_index}][key]", params['ingredients']["#{i.first}"]['key'], class: "form-control" %>
                            </div>
                        </div>
                        <div class="col">
                            <div class="mb-3">
                                <%= label_tag "ingredients[#{i_index}][value]","amount", class: 'form-label' %>
                                <%= number_field_tag "ingredients[#{i_index}][value]", params['ingredients']["#{i.first}"]['value'], class: "form-control" %>
                            </div>
                        </div>
                        <div class="col-2 align-self-center">
                            <%= link_to "remove", "javascript:remove_ingredients_item(#{i_index})", class: 'link-danger' %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <%= link_to "+ item", "javascript:add_ingredients_item()", class: 'btn btn-link'%>
    </div>
</div>

app/views/cakes/_recipe.html.erb
<div class="card">
    <div class="card-body">
        <h4>Recipe:</h4>
        <div id="recipe">
            <% if params['recipe'].present? %>
                <% r_index = 0 %>
                <% params['recipe'].each do |r| %>
                    <% r_index += 1 %>
                    <div class="row recipe_item <%= "recipe-#{r_index}" %>">
                        <div class="col">
                            <div class="mb-3">
                                <%= label_tag "recipe[#{r_index}][key]","name", class: "form-label" %>
                                <%= text_field_tag "recipe[#{r_index}][key]", params['recipe']["#{r.first}"]['key'], class: "form-control" %>
                            </div>
                        </div>
                        <div class="col">
                            <div class="mb-3">
                                <%= label_tag "recipe[#{r_index}][value]","amount", class: "form-label" %>
                                <%= number_field_tag "recipe[#{r_index}][value]", params['recipe']["#{r.first}"]['value'], class: "form-control" %>
                            </div>
                        </div>
                        <div class="col-2 align-self-center">
                            <%= link_to "remove", "javascript:remove_recipe_item(#{r_index})", class: 'link-danger' %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <%= link_to "+ item", "javascript:add_recipe_item()", class: 'btn btn-link'%>
    </div>
</div>

app/views/cakes/_result.html.erb
<% if @cake_result.present? %>
    <div class="alert alert-success " role="alert">
        <h3>Result: </h3>
        <h4>You can make <%= pluralize(@cake_result, 'cake') %> </h4>
    </div>
<% end %>

app/views/cakes/index.html.erb
<%= form_tag cakes_calculate_cake_path(), method: :post do %>
    <div class="row">
        <div class="col">
            <%= render "recipe"%>
        </div>

        <div class="col">
            <%= render "ingredients"%>
        </div>
    </div>
    <br>
    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary">Calculate</button>
    </div>
    <br>
<% end %>

<%= render "result" %>

<script>
    let total_ingredients = document.getElementsByClassName('ingredient_item').length
    let total_recipes = document.getElementsByClassName('recipe_item').length

    add_ingredients_item = () => {
        total_ingredients += 1

        document.getElementById('ingredients').insertAdjacentHTML("beforeend", `<div class="row ingredient_item ingredients-${total_ingredients}"><div class="col"><div class="mb-3"><label class="form-label" for="ingredients_${total_ingredients}_key">name</label><input type="text" name="ingredients[${total_ingredients}][key]" id="ingredients_${total_ingredients}_key" class="form-control"></div></div><div class="col"><div class="mb-3"><label class="form-label" for="ingredients_${total_ingredients}_value">amount</label><input type="number" name="ingredients[${total_ingredients}][value]" id="ingredients_${total_ingredients}_value" class="form-control"></div> </div><div class="col-2 align-self-center"><a class="btn btn-default link-danger" href="javascript:remove_ingredients_item(${total_ingredients})">remove</a></div></div>`);

        return false
    }

    add_recipe_item = () => {
        total_recipes += 1

        document.getElementById('recipe').insertAdjacentHTML("beforeend", `<div class="row recipe_item recipe-${total_recipes}"><div class="col"><div class="mb-3"><label class="form-label" for="recipe_${total_recipes}_key">name</label><input type="text" name="recipe[${total_recipes}][key]" id="recipe_${total_recipes}_key" class="form-control"></div></div><div class="col"><div class="mb-3"><label class="form-label" for="recipe_${total_recipes}_value">amount</label><input type="number" name="recipe[${total_recipes}][value]" id="recipe_${total_recipes}_value" class="form-control"></div> </div><div class="col-2 align-self-center"><a class="btn btn-default link-danger" href="javascript:remove_recipe_item(${total_recipes})">remove</a></div></div>`)
        return false
    }

    remove_ingredients_item = (item_index) => {
        const elements = document.getElementsByClassName(`ingredients-${item_index}`);
        while(elements.length > 0){
            elements[0].parentNode.removeChild(elements[0]);
        }
    }

    remove_recipe_item = (item_index) => {
        const elements = document.getElementsByClassName(`recipe-${item_index}`);
        while(elements.length > 0){
            elements[0].parentNode.removeChild(elements[0]);
        }
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exercise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar bg-primary">
      <div class="container">
        <a class="navbar-brand text-bg-primary" href="#">Cake calculator</a>
      </div>
    </nav>
    <div class="container">
      <br>
      <% if notice.present? %>
          <div class="alert alert-warning" role="alert">
              <%= notice%>
          </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>